[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "development"
  NODE_VERSION = "22"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
  # NODE_ENV is automatically set to "production" — no need to define it

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true

