[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"

# For Next.js sites, use built-in Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"

# Build cache configuration
[build.processing]
  skip_processing = false
